trigger:
- main

pool:
  name: 'azrhrfvm'   # self-hosted agent pool name

stages:
- stage: TerraformValidate
  jobs:
    - job: TerraformValidateJob
      continueOnError: false
      steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish Artifacts
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/Git-Repo-Files/terraform-manifests'
          artifact: 'terraform-manifests-out'
          publishLocation: 'pipeline'

      - script: |
          sudo apt-get update
          sudo apt-get install -y unzip wget   # <-- Added this line
          curl -LO https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
          unzip terraform_1.9.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version
        displayName: "Install Terraform"

      - script: |
          terraform init \
            -backend-config="resource_group_name=azr-hrf" \
            -backend-config="storage_account_name=azrhrfvm" \
            -backend-config="container_name=tfstatefiles" \
            -backend-config="key=aks-base.tfstate"
        workingDirectory: $(System.DefaultWorkingDirectory)/Git-Repo-Files/terraform-manifests
        displayName: "Terraform Init"

      - script: terraform validate
        workingDirectory: $(System.DefaultWorkingDirectory)/Git-Repo-Files/terraform-manifests
        displayName: "Terraform Validate"
