trigger:
- main

pool:
  name: 'azrhrfvm'   # This is your self-hosted agent pool name
  demands:
  - Agent.OS -equals Linux   # Ensures it runs on your Linux VM agent

stages:
- stage: TerraformValidate
  jobs:
    - job: TerraformValidateJob
      continueOnError: false
      steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish Artifacts
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/Git-Repo-Files/terraform-manifests'
          artifact: 'terraform-manifests-out'
          publishLocation: 'pipeline'

      # Optional: If Terraform is already installed on your self-hosted VM, you can remove this step
      - task: TerraformInstaller@0
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest'

      - task: TerraformCLI@0
        displayName: Terraform Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Git-Repo-Files/terraform-manifests'
          backendType: 'azurerm'
          backendServiceArm: 'terraform-aks-azurerm-svc-con'
          backendAzureRmResourceGroupName: 'azr-hrf'
          backendAzureRmStorageAccountName: 'azrhrfvm'
          backendAzureRmContainerName: 'tfstatefiles'
          backendAzureRmKey: 'aks-base.tfstate'
          allowTelemetryCollection: false

      - task: TerraformCLI@0
        displayName: Terraform Validate
        inputs:
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Git-Repo-Files/terraform-manifests'
          allowTelemetryCollection: false
